### ISSUE TITLE
panic on empty .pi.toml

### ISSUE THREAD

**Issue by sanga** [vmchale/project-init#6]
At least I'm guessing this is related to the fact that my .pi.toml is empty.

Against v 2.9.7

```
RUST_BACKTRACE=1 pi l                                                                                                        

thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Some(69)`,
 right: `Some(10)`', /home/tsampson/.cargo/registry/src/github.com-1ecc6299db9ec823/project_init-2.9.7/src/main.rs:70:26
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:71
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   2: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:397
             at /checkout/src/libstd/panicking.rs:577
   3: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   4: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   5: pi::main
   6: main
   7: __libc_start_main
   8: _start
```

**Comment by vmchale** [comment]
Should be fixed now. Thanks for the bug report!
